### ISSUE TITLE
xg_vit_model_covid_2d.pt

### ISSUE THREAD

**Issue by antoniaaaaaaaaaaaa** [xiaohong1/COVID-ViT#8]
https://drive.google.com/drive/folders/1nBI02F-8Y0hFeN10CMu9Svj4xRViN5xt
这个链接里面有xg_vit_model_covid_2d.pt吗？我只看到了xg_vit_model_covid_3d.pt和xg_vit_model_covid.pt
我下载了后者发现不对，请问哪里有xg_vit_model_covid_2d.pt吗？

**Comment by xiaohong1** [comment]
xg_vit_model_covid.pt = xg_vit_model_covid_2d.pt
